# -*- mode: sh -*-

echo "bashrc"

[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completionexport PATH="/usr/local/opt/sqlite/bin:$PATH"

# load shopify-app-cli, but only if present and the shell is interactive
# if [[ -f "/Users/devil/.shopify-app-cli/shopify.sh" ]]; then source "/Users/devil/.shopify-app-cli/shopify.sh"; fi

# this file gets run in two cases:
# 1. non-login interactive shell
# 2. remote shell (over ssh or similar)

# #2 happens when you run "ssh user@host bash" explicitly.
# in this case, /etc/bash.bashrc has not been previous executed (unlike #1).
# however, we assume that #2 is a recovery mode, so we don't want to do much.
# (also, my google-fu didn't find a way to distinguish them)

. ~/.bash/env
. ~/.bash/interactive
