# -*- mode: sh -*-

echo "zshrc"

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# emacs mode

.zsh/interactive

bindkey -e

export ZSH=$HOME/.oh-my-zsh

# source $HOME/.dotenv/env.sh
# source $ZSH_DOT/utils.sh
# source $ZSH_DOT/history.sh
# source $ZSH_DOT/vimify.sh

# source $ZSH_DOT/mandatory_aliases.sh
# source $ZSH_DOT/explicit_aliases.sh

# ZSH_DOT="$DOTENV/zsh/"
# DOTENV="$HOME/.dotenv/"

# completions
# source $DOTENV/completion/tmuxinator.zsh

# Path to your oh-my-zsh installation.

ulimit -n 200000
ulimit -u 2048

ZSH_THEME="robbyrussell"

DISABLE_AUTO_UPDATE="true"

# don't share commands history between sessions
unsetopt share_history

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.

# 10ms for key sequences
KEYTIMEOUT=1

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(zsh-autosuggestions gitfast) #  wp-cli

. $ZSH/oh-my-zsh.sh

# User configuration
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=4"

# don't share commands history between sessions
unsetopt share_history
# export MANPATH="/usr/local/man:$MANPATH"

# Print current directory content after every pwd change
# add-zsh-hook -Uz chpwd (){ ls; }
# autoload -U add-zsh-hook

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# fix emacs tramp login issue
# [ $TERM = "dumb" ] && unsetopt zle && PS1='$ '

# if command -v pyenv 1>/dev/null 2>&1; then
  # eval "$(pyenv init -)"
# fi

# added by travis gem
# [ ! -s /Users/devil/.travis/travis.sh ] || source /Users/devil/.travis/travis.sh

# autoload -U +X bashcompinit && bashcompinit
# complete -o nospace -C /usr/local/bin/terraform terraform

export NVM_DIR="$HOME/.nvm"

if [ -s "~/.zshrc_local" ]; then
  . ~/.zshrc_local
fi
