call plug#begin('~/.vim/plugged')

" Plug 'vim-syntastic/syntastic'
" Plug 'altercation/vim-colors-solarized'
" Plug 'scrooloose/nerdcommenter'
" Plug 'ervandew/supertab'

" Tmux
Plug 'christoomey/vim-tmux-navigator'
Plug 'benmills/vimux'

" General
" Plug 'tpope/vim-vinegar'

" Devel
Plug 'vim-scripts/SyntaxComplete'
Plug 'vim-scripts/XSLT-syntax'
Plug 'plasticboy/vim-markdown'
Plug 'tpope/vim-git'
Plug 'docker/docker' , {'rtp': '/contrib/syntax/vim/'}
Plug 'dag/vim-fish'
Plug 'elzr/vim-json'
Plug 'stephpy/vim-yaml'
Plug 'lfilho/cosco.vim'

" Web
Plug 'othree/html5.vim'
Plug 'JulesWang/css.vim'
Plug 'ap/vim-css-color'
Plug 'digitaltoad/vim-pug'
Plug 'groenewege/vim-less'
Plug 'wavded/vim-stylus'
Plug 'benjifisher/matchit.zip'

" Python
Plug 'mitsuhiko/vim-python-combined'
Plug 'aliev/vim-compiler-python'

" Ruby
Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-rails'
Plug 'sheerun/vim-yardoc'

" PHP
Plug 'StanAngeloff/php.vim'
Plug 'mxw/vim-xhp'

" Javascript
Plug 'othree/javascript-libraries-syntax.vim'
Plug 'glanotte/vim-jasmine'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'leafgarland/typescript-vim'
Plug 'othree/yajs.vim'
Plug 'jason0x43/vim-js-indent'
Plug 'maksimr/vim-jsbeautify'
" Plug 'moll/vim-node'


" Plug 'wookiehangover/jshint.vim'
" Lint engine
" Plug 'w0rp/ale'

" Plug 'tpope/vim-speeddating'
Plug 'henrik/vim-indexed-search'
" Plug 'janko-m/vim-test'
" Plug 'skywind3000/asyncrun.vim'
Plug 'victormours/better-writing.vim'
" Plug 'vim-scripts/CursorLineCurrentWindow'
" Plug 'yegappan/mru'
Plug 'tpope/vim-repeat'
Plug 'mattn/emmet-vim'
" Plug 'csscomb/vim-csscomb'
Plug 'othree/xml.vim'
" Plug 'alvan/vim-closetag'
" Plug '1995eaton/vim-better-javascript-completion'
Plug 'AndrewRadev/splitjoin.vim'
" Plug 'kana/vim-textobj-user'
" Plug 'vim-scripts/ConflictMotions'
" Plug 'skammer/vim-css-color'
Plug 'godlygeek/tabular'
" Plug 'flowtype/vim-flow'
" Plug 'vim-scripts/Conque-Shell'
" Plug 'Chiel92/vim-autoformat'
" Plug 'scrooloose/syntastic'
" Plug 'ternjs/tern_for_vim'
" Plug 'bling/vim-airline'
Plug 'osyo-manga/vim-anzu'
" Plug 'Valloric/YouCompleteMe'
Plug 'SirVer/ultisnips'
Plug 'mhartington/vim-typings'
" Plug 'Shougo/unite.vim'
" Plug 'https://github.com/xolox/vim-easytags.git'
" Plug 'https://github.com/vim-scripts/YankRing.vim.git'
Plug 'craigemery/vim-autotag'
Plug 'majutsushi/tagbar'
Plug 'xolox/vim-misc'
" Plug 'https://github.com/xolox/vim-session.git'
Plug 'airblade/vim-gitgutter'
Plug 'Quramy/vim-js-pretty-template'
Plug 'Quramy/tsuquyomi'
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
Plug 'HerringtonDarkholme/yats.vim'
Plug 'Olical/vim-enmasse'
" Plug 'https://github.com/vim-scripts/cscope.vim'
Plug 'vim-scripts/PreserveNoEOL'
Plug 'editorconfig/editorconfig-vim'
Plug 'aperezdc/vim-template'
Plug 'Townk/vim-autoclose'
Plug 'tomtom/tcomment_vim'
" Plug 'git://github.com/tpope/vim-cucumber.git'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
" Plug 'nathanaelkane/vim-indent-guides'
Plug 'flazz/vim-colorschemes'
Plug 'mileszs/ack.vim'
" Plug 'scrooloose/nerdtree'
" Plug 'jistr/vim-nerdtree-tabs'
" Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'othree/jsdoc-syntax.vim'
Plug 'heavenshell/vim-jsdoc'
Plug 'itspriddle/vim-jquery'
Plug 'othree/javascript-libraries-syntax.vim'
" Plug 'othree/jspc.vim'
" Plug 'severin-lemaignan/vim-minimap'
" Plug 'sheerun/vim-polyglot'
Plug 'ctrlpvim/ctrlp.vim'

" Add plugins to &runtimepath
call plug#end()

" ================================================
" General
" ================================================
set nocompatible
filetype on
filetype plugin on
filetype indent on
set encoding=utf-8
set spelllang=en
set number
set ruler
set showcmd " show me what I'm typing
set laststatus=2
set wrap
set splitbelow " opens next horizontal window below current
set mouse=a
set mousemodel=popup
set ignorecase
" autoread file changes
set autoread
set tabstop=2
set shiftwidth=2
set expandtab
" copy to system clipboard
set clipboard+=unnamed
" Hide Vim Intro
set shortmess+=I
" Hightlight Current Line
set cursorline
" Redraw ONLY When Need To
set lazyredraw
" Enable Magic for Regular Expression
set magic
" Treat Long Lines as Break Lines
set ai " auto indent
set si " smart indent
set shell=sh
" set relativenumber
" set smartcase
set noswapfile
set backspace=2
syntax on
set foldmethod=marker
set omnifunc=syntaxcomplete#Complete
set complete-=t
set hlsearch
set incsearch
set wildmenu
set guioptions-=r
set guioptions-=L
set guicursor=n-v-c:blinkon0
set scrolloff=999
let mapleader = ","
set splitright
set wildignore=**/*.bak,**/*.pyc,**/*.class,**/node_modules/**,**/dist/**,**/compiled/**,**/docs/**,**/target/**
set wildignore+=**/*.zip,**/*.tar.gz,**/*.tar.bz2,**/*.rar,**/*.tar.xz
set wildignore+=**/vendor/gems/*,**/vendor/cache/*,**/.bundle/*,**/.sass-cache/*
set wildignore+=**/*.o,**/*.out,**/*.obj,**/.git,**/*.rbc,**/*.rbo,**/.svn,**/.gem
set wildignore+=**/.swp,**/*~,**/._*
set noequalalways
set secure " not allow shell and write commands in autocmd
set exrc " allow project specific .vimrc files
set timeout timeoutlen=1000 ttimeoutlen=100 " remove `O` and `o` Delay
set nopaste
set visualbell

" Search down into subfolders
" Provides tab-completition for all file-related tasks
set path=**

highlight OverLength  ctermfg=white guibg=#592929
match OverLength /\%100v.\+/
set colorcolumn=100

augroup General_Autocmd
  autocmd!
  " Write variable s:std_in if arguments for VIM was passed
  autocmd StdinReadPre * let s:std_in=1
  autocmd BufNewFile,BufRead *.es6,*.tsx set ft=javascript.jsx
  autocmd BufNewFile,BufRead *.es6,*.tsx,*.jsx :ia <buffer> </ </<C-X><C-O>>
  autocmd VimEnter * call RestoreSession()
  " Open netrw if no arguments were passed to VIM and diff mode is off
  autocmd VimEnter * if argc() == 0 && !exists('s:std_in') && !&diff | execute 'windo :Explore' | endif
augroup END

function! McopyFilePathToClipboard()
  redir @*
  echo expand('%:p:h')
  redir END
endfunction

nnoremap <leader>cf :call McopyFilePathToClipboard()<cr>

" Delete strings without poluting last yank buffer
nnoremap <leader>d "_d
nnoremap <leader>x "_x
nnoremap <leader>c "_c
nnoremap <leader>dw "_dw
nnoremap <leader>xw "_xw
nnoremap <leader>cw "_cw
nnoremap <leader>de "_de
nnoremap <leader>xe "_xe
nnoremap <leader>ce "_ce

" Reload vim ~/.vimrc
command! ReloadConfig so ~/.vimrc | echom 'Config reloaded'

" Copy word under the cursor to clipboard
nnoremap <leader>c viwy

" Search for word under cursor.
nnoremap <C-h> :help <C-r><C-w><cr>

" let g:cssColorVimDoNotMessMyUpdatetime = 1

" noremap <Up> <Nop>
" noremap <Down> <Nop>
" noremap <Left> <Nop>
" noremap <Right> <Nop>

" Remove ex mode
nnoremap Q <nop>

" Show search occourences count in statusbar
" set statusline=%{anzu#search_status()}
" nmap n <Plug>(anzu-n-with-echo)
" nmap N <Plug>(anzu-N-with-echo)
" nmap * <Plug>(anzu-star-with-echo)
" nmap # <Plug>(anzu-sharp-with-echo)
" nmap <Esc><Esc> <Plug>(anzu-clear-search-status)

let g:closetag_filenames = "*.html,*.xhtml,*.phtml"

" ================================================
" Tmux Support
" ================================================

" Write all buffers before navigating from Vim to tmux pane
let g:tmux_navigator_save_on_switch = 2

" ================================================
" VImux - Tmux plugin
" ================================================
" Inspect runner pane
nnoremap <leader>vi :VimuxInspectRunner<cr>

" Zoom the tmux runner pane
nnoremap <leader>vz :VimuxZoomRunner<cr>

" Disable tmux navigator when zooming the Vim pane
" let g:tmux_navigator_disable_when_zoomed = 1

" Change root directory to local file dir
nnoremap <silent> <leader>cd :cd %:p:h<cr>

" ================================================
" Emmet
" ================================================

let g:user_emmet_install_global = 0
let g:user_emmet_leader_key='<leader>z'
let g:user_emmet_mode='a'

" ================================================
" Windows & splits manipulaton
" ================================================

" easier cycling and delete buffers in current window
nnoremap gb :bn<cr>
nnoremap gp :bp<cr>
nnoremap <silent> <LEADER>gd :bd<cr>

" Toggle horizontal/vertical split
function! ToggleWindowHorizontalVerticalSplit()
  if !exists('t:splitType')
    let t:splitType = 'vertical'
  endif

  if t:splitType == 'vertical' " is vertical switch to horizontal
    windo wincmd K
    let t:splitType = 'horizontal'

  else " is horizontal switch to vertical
    windo wincmd H
    let t:splitType = 'vertical'
  endif
endfunction

nnoremap <silent> <leader>wt :call ToggleWindowHorizontalVerticalSplit()<cr>

function! DeleteHiddenBuffers()
  let tpbl=[]
  call map(range(1, tabpagenr('$')), 'extend(tpbl, tabpagebuflist(v:val))')
  for buf in filter(range(1, bufnr('$')), 'bufexists(v:val) && index(tpbl, v:val)==-1')
    silent! execute 'bwipeout!' buf
  endfor
  echom "Hidden buffers wiped out!"
endfunction

nnoremap <silent> <leader>bw :call DeleteHiddenBuffers()<cr>

function! AlignBuffer()
  let l:isPHP = 0

  if &ft ==# 'php'
    let l:isPHP = 1
    setl ft=html
  endif

  exe "normal! mm"
  exe "normal! gg"
  exe "normal! VG"
  exe "normal! ="
  exe "normal! 'm"

  if l:isPHP
    setl ft=php
  endif
endfunction

nnoremap <leader>w= :call AlignBuffer()<cr>

" ================================================
" Select Mode
" ================================================
" nnoremap § *``gn<C-g>
" inoremap § <C-o>gn<C-g>
" snoremap <expr> . @.

" ================================================
" Search & Replace
" ================================================
" Search for phrase mached in Visual Mode with //
" vnoremap <expr> // 'y/\V'.escape(@",'\').'<cr>'")
" nnoremap * /\<cword
" command! Mdiffoff nnoremap <buffer> ] <nop>|nnoremap <buffer> [ <nop>|diffoff

" goto first editable window
" au VimEnter * :exe "winc l"

" Count occourences of selected text.
nnoremap <leader>* *<C-O>:%s///gn<cr>

" Remove empty lines
command! MremoveEmptyLines g/^\s*$/d

" ================================================
" QuickFix
" ================================================

nnoremap <silent> <leader>q :call QuickfixToggle()<cr>

let g:quickfix_is_open = 0
let g:quickfix_return_to_window = winnr()

function! QuickfixToggle()
  if g:quickfix_is_open
    cclose
    let g:quickfix_is_open = 0
    execute g:quickfix_return_to_window . "wincmd w"
  else
    let g:quickfix_return_to_window = winnr()
    copen
    let g:quickfix_is_open = 1
  endif
endfunction

" ================================================
" Plain Text mode
" ================================================

" ================================================
" CSSComb
" ================================================
" autocmd FileType css,scss noremap <buffer> <leader>bc :CSScomb<cr>

" ================================================
" Diff
" ================================================
set diffopt+=iwhite

" these two are probably not needed
" command! Mdiffthis nnoremap <buffer> ] ]c|nnoremap <buffer> [ [c|diffthis
" command! Mdiffoff nnoremap <buffer> ] <nop>|nnoremap <buffer> [ <nop>|diffoff

if &diff
  nnoremap <leader>1 :diffget LOCAL<cr>
  nnoremap <leader>2 :diffget BASE<cr>
  nnoremap <leader>3 :diffget REMOTE<cr>
endif

augroup Diff_Autocmd
  autocmd!
  autocmd VimEnter * if &diff | execute 'windo set wrap' | endif
augroup END

" ================================================
" Snippets
" ================================================
set runtimepath+=~/.vim/my-snippets/
" let g:UltiSnipsSnippetsDir = '~/.vim/my_snippets/'
let g:UltiSnipsSnippetDirectories = ['ultisnips']
let g:UltiSnipsEditSplit = 'vertical'

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<C-j>"
let g:UltiSnipsJumpBackwardTrigger="<C-k>"
let g:UltiSnipsListSnippets='<C-tab>'

" let g:SuperTabDefaultCompletionType    = '<C-n>'
" let g:SuperTabCrMapping                = 0
" let g:UltiSnipsExpandTrigger           = '<tab>'
" let g:UltiSnipsJumpForwardTrigger      = '<tab>'
" let g:UltiSnipsJumpBackwardTrigger     = '<s-tab>'
" let g:ycm_key_list_select_completion   = ['<C-j>', '<C-n>', '<Down>']
" let g:ycm_key_list_previous_completion = ['<C-k>', '<C-p>', '<Up>']

" ================================================
" General Mapings & Ab
" ================================================
" Fix indentation
noremap <leader><F7> mzgg=G`z
" Copy to clipboard
" vnoremap <leader><C-c> :w !pbcopy<cr><cr>
" Paste from clipboard
" noremap <leader><C-v> :r !pbpaste<cr><cr>
" vnoremap <C-c> :w !pbcopy<cr><cr>
" noremap <C-v> :r !pbpaste<cr><cr>
nnoremap j gj
nnoremap k gk

noremap <Up> gk
noremap <Down> gj
ounmap <Up>
ounmap <Down>

" search for visualy selected text
vnoremap * y/<C-R>"<cr>"

" close all buffers except current one
nnoremap <silent> <leader>bd :%bd\|e# <cr>

" Goto local definition and add mark to starting line
nnoremap gd mm gd
" nnoremap gg mm gg
" nnoremap G mm G

" Quick Toggle Background BEtween Dark & Light
nnoremap <leader>Tn :let &background=(&background=="dark"?"light":"dark")<cr>

" ================================================
" Sessions
" ================================================
if has('gui_running')
  set background=dark
  " colorscheme gruvbox
  colorscheme monokai
  " znake, zmrok, wolfpack,
  " Fullscreen mode
  set lines=9999 columns=9999
  " colorscheme monokai
  " set termguicolors
  " " colorscheme darkblue
  " let g:session_autosave = 'yes'
  " let g:session_autoload = 'yes'
else
  " colorscheme phd
  colorscheme monokai
  " let g:session_autosave = 'no'
endif

" ================================================
" EditorConfig
" ================================================
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
let g:EditorConfig_exec_path = '/usr/local/bin/editorconfig'
let g:EditorConfig_core_mode = 'external_command'

" ================================================
" Tagbar
" ================================================
noremap <leader>tb :TagbarToggle<cr>
" ================================================
" NERDTree
" ================================================
" let NERDTreeIgnore = ['cscope.*', '.*\.xd', 'tags', '.DS_Store', '.git', 'node_modules']
" let NERDTreeWinSize = 40
" let NERDTreeShowHidden = 1
"
" " Less verbose NERDTree UI
" let NERDTreeMinimalUI = 1
"
" " Automatically delete buffer of the deleted file from NERDTree
" let NERDTreeAutoDeleteBuffer = 1
"
" let g:nerdtree_tabs_open_on_gui_startup = 2
" let g:nerdtree_tabs_open_on_console_startup = 2
" let g:nerdtree_tabs_focus_on_files = 1
" let g:nerdtree_tabs_autofind = 0
"
" noremap <leader><F2> :NERDTreeFind<cr>
" noremap <leader>k :NERDTreeToggle<cr>

" Jump to other window then NERDTree on VIM enter
" autocmd VimEnter * wincmd p

" Write variable s:std_in if arguments for VIM was passed
" autocmd StdinReadPre * let s:std_in=1

" Open NERDTree if no arguments were passed to VIM and diff mode is off
" autocmd VimEnter * if argc() == 0 && !exists('s:std_in') && !&diff | execute 'windo :NERDTree' | endif

" Close VIM when NERDTree is the last opened window
" autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" ================================================
" Git - gutter
" ================================================
set updatetime=250
command! -nargs=? MGitBase call SetGitGutterBase(<f-args>)

function! SetGitGutterBase(...)
  let g:gitgutter_diff_base = a:0 == 0 ? '' : a:1
  echo 'g:gitgutter_diff_base: ' . g:gitgutter_diff_base
  GitGutter
endfunction

" ================================================
" Session
" ================================================
" function! SaveSess()
"   let filename = getcwd() . '/Session.vim'
"   if filereadable(filename)
"     execute 'mksession! ' . getcwd() . '/Session.vim'
"   endif
" endfunction

" Restore VIM session if ./Session.vim file exists.
function! RestoreSession()
  let l:filename = getcwd() . '/Session.vim'
  if filereadable(l:filename)
    execute 'so ' . l:filename
  endif
endfunction

" autocmd VimLeave * call SaveSess()

" ================================================
" Git - Fugitive
" ================================================
autocmd QuickFixCmdPost *grep* cwindow

set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P

" ================================================
" Fuzz Search - find any phrase in all files
" ================================================
nnoremap <leader>f :call FuzzSearch()<cr>
vnoremap <leader>f :call FuzzSearchVisual()<cr>

function! FuzzSearch()
  let l:phrase = input('What pattern? ', expand('<cword>'))
  if empty(l:phrase)
    return
  endif

  let l:folder = input('What folder? ')
  if empty(l:folder)
    return
  endif

  call FuzzSearchForPhrase(l:phrase, l:folder)
endfunction

function! FuzzSearchForPhrase(phrase, folder)
  " Create new horizontal split for opening file from results
  silent! exe "new"
  let l:previewWin = winnr()

  " Move new split to the bottom
  silent! exe "normal! \<C-w>J"

  " let l:wasNERDTreeOpened = 0

  " Check if NERDTree is opened and close if it is
  " if g:NERDTree.IsOpen()
  "   let l:wasNERDTreeOpened = 1
  "   exe "NERDTreeClose"
  " endif

  exe ":Ack --smart-case '" . a:phrase . "'  '" . a:folder . "'"
  let g:quickfix_is_open = 1

  " Restore nerd tree if was open
  " if l:wasNERDTreeOpened
  "   exe "NERDTree"
  "   let l:pom = winnr('$') - 1
  "   exe "normal! " l:pom . "\<C-W>w"
  "   exe "resize +5"
  "   exe "normal! " winnr('$') . "\<C-W>w"
  " endif
endfunction

function! FuzzSearchVisual()
  let l:phrase = getline("'<")[getpos("'<")[2]-1:getpos("'>")[2]-1]
  let l:folder = input('What folder? ')

  if empty(l:folder)
    let l:folder = '.'
  endif

  call FuzzSearchForPhrase(l:phrase, l:folder)
endfunction

if executable('ag')
  let g:ackprg = 'ag --nogroup --nocolor --column'
  let g:ag_working_path_mode="r"
endif

" ================================================
" ctags
" ================================================

let g:autotagTagsFile="tags"

command! Ctags !ctags -R .

" ================================================
" CSCOPE - ctags alternative
" ================================================
" if has("cscope")
"   nnoremap <leader>fz :tab :call cscope#findInteractive(expand('<cword>'))<cr>
"   nnoremap <leader>l :call ToggleLocationList()<cr>
"   set csprg=/usr/local/bin/cscope
"   set csto=0
"   set cst
"   set nocsverb
"
"   if filereadable("cscope.out")
"     cs add cscope.out
"   endif
"   set csverb
" endif

" ================================================
" Tabularize
" ================================================
if exists(":Tabularize")
  noremap <leader>a= :Tabularize /=<cr>
  noremap <leader>a: :Tabularize /:\zs<cr>

  " tabularize on every | char
  " inoremap <silent> <Bar>   <Bar><Esc>:call <SID>align()<cr>a
  " function! s:align()
  "   let p = '^\s*|\s.*\s|\s*$'
  "   if getline('.') =~# '^\s*|' && (getline(line('.')-1) =~# p || getline(line('.')+1) =~# p)
  "     let column = strlen(substitute(getline('.')[0:col('.')],'[^|]','','g'))
  "     let position = strlen(matchstr(getline('.')[0:col('.')],'.*|\s*\zs.*'))
  "     Tabularize/|/l1
  "     normal! 0
  "     call search(repeat('[^|]*|',column).'\s\{-\}'.repeat('.',position),'ce',line('.'))
  "   endif
  " endfunction
endif

" ================================================
" CTRLP - find particular file
" ================================================
let g:ctrlp_use_caching = 1
let g:ctrlp_regexp = 1
let g:ctrlp_by_filename = 1
let g:ctrlp_mruf_max = 25
let g:ctrlp_tilde_homedir = 1
let g:ctrlp_mruf_relative = 1
let g:ctrlp_types = ['fil', 'mru', 'buf']
let g:ctrlp_mruf_case_sensitive = 1
let g:ctrlp_mruf_save_on_update = 1
let g:ctrlp_switch_buffer = 'e'
let g:ctrlp_custom_ignore = {
      \ 'dir':  '\v[\/]((\.(git|hg|svn))|node_modules|cscope.*|build.*|dist.*)',
      \ 'file': '\v\.(exe|so|dll)$',
      \ 'link': 'SOME_BAD_SYMBOLIC_LINKS'
      \ }

" Search by ctags
nnoremap <leader>t :CtrlPTag<cr>
nnoremap <leader>l :CtrlPMRU<cr>
" nnoremap <leader>q :CtrlPQuickFix<cr>

function! HTMLOpenFunc(action, line)
  if a:action =~ '^[tx]$' && fnamemodify(a:line, ':e') =~? '^html\?$'
    " Get the filename
    let filename = fnameescape(fnamemodify(a:line, ':p'))

    " Close CtrlP
    call ctrlp#exit()

    " Open the file
    if has('mac')
      silent! execute '!open' filename
    else " is Linux
      silent! execute '!xdg-open' filename
    endif
  elseif a:action == 'x' && fnamemodify(a:line, ':e') !~? '^html\?$'
    " Not a HTML file, simulate pressing <c-o> again and wait for new input
    call feedkeys("\<c-o>")

  else
    " Use CtrlP's default file opening function
    call call('ctrlp#acceptfile', [a:action, a:line])
  endif
endfunction

let g:ctrlp_open_func = {'files': 'HTMLOpenFunc'}

" ================================================
" Templating
" ================================================
" fun! InsertFileManifest(file)
"   if empty(glob(a:file))
"     let cwd = fnamemodify(getcwd(), ':t')
"     let filename = "~/.vim/signatures/" . cwd . ".txt"
"
"     if !empty(glob(filename))
"       exe "-1r " . filename
"       call EvalTemplateVariables()
"     endif
"   endif
" endfun

" fun! EvalTemplateVariables()
"   if line("$") > 20
"     let l = 20
"   else
"     let l = line("$")
"   endif
"   exe "1," . l . "g/<copy-date>/s/<copy-date>/" . strftime("%Y")
" endfun

" fun! MyComment()
"   let l:winview = winsaveview()
"   :go1
"   tcomment#Comment()
"   " call winrestview(l:winview)
"   " let @q ='msgggcc\`s'
"   " @q
" endfun

" autocmd BufFilePre,BufWritePre * ks|call InsertFileManifest(expand('<afile>'))|'s

" fun! ApplySkeletonDevs()
"   let cwd = fnamemodify(getcwd(), ':t')
"   let skeletons_path = "~/.vim/skeletons/"
"   let filename = skeletons_path . cwd
"   if !empty(glob(filename))
"     let g:templates_directory = filename
"
"     " let skeletons = system("ls " . filename)
"     "
"     " for s:item in split(skeletons)
"     "   " echo "autocmd BufNewFile *." . substitute(s:item,'.*\.', '', '') .	"0r skeletons_path" . s:item
"     "   let file_ext = substitute(s:item,'.*\.', '.', '')
"     "   let file_skeleton = join([skeletons_path, s:item])
"     "   let skeleton_ext = substitute(s:item, '.*\.', '.', '')
"     "   " autocmd BufNewFile file_ext	0r file_skeleton
"     "   echo '_' . s:item . '_ file_ext: ' . file_ext . ' skeleton:ext: ' . skeleton_ext
"     "   autocmd BufNewFile *.*	0r call InsertFile(expand('%'), file_skeleton, skeleton_ext)
"     " endfor
"
"     " autocmd BufNewFile  *.c	0r ~/vim/skeleton.c
"     " exe "-1r " . filename
"     " call EvalTemplateVariables()
"   endif
" endfun

" fun! InsertFile(file, skeleton, skeleton_ext)
"   echo '_a:file' . a:file . '_'
"   let file_ext = substitute(a:file, '.*\.', '.', '')
"   if file_ext == a:skeleton_ext
"     :read a:skeleton
"   endif
" endfun

" let g:templates_directory =
let g:username = $USERNAME
let g:email = $EMAIL
let g:license = 'Proprietary'
let g:templates_user_variables = []

if $AOL == 'true'
  let g:templates_directory = '~/.vim/templates/aol/'
else
  let g:templates_directory = '~/.vim/templates/private/'
end

" call ApplySkeletonDevs()
" autocmd VimEnter * call ApplySkeletonDevs()

function! GetCurrentContent()
  let l:content = getline(0,line("$"))
  let l:result = 0
  for l:temp in l:content
    if strlen(l:temp) > 0
      let l:result = 1
      break
    endif
  endfor
  if l:result == 0
    let l:extension = expand("%:c")
    exe 'Template .' . l:extension
  endif
endfunction

autocmd BufEnter * call GetCurrentContent()

function! ExecuteMacroOverVisualRange()
  echo "@".getcmdline()
  execute ":'<,'>normal @".nr2char(getchar())
endfunction

xnoremap @ :<C-u>call ExecuteMacroOverVisualRange()<cr>

" ================================================
" Netrw
" ================================================

augroup Netrw_Autocmd
  autocmd!
  autocmd FileType netrw call SetupNetrwEnv()
augroup END

function! SetupNetrwEnv()
  if !exists('w:netrwSet')
    setl bufhidden=delete
    setl buftype=nofile
    noremap <buffer> gp :bprevious<cr>
    noremap <buffer> gb :bnext<cr>
    let w:netrwSet = 1
  endif
endfunction

let g:netrw_use_errorwindow = 0 " show netrw messages as echoerr
let g:netrw_localmkdir = 'mkdir -p '
let g:netrw_banner = 0 " disable banner
let g:netrw_browse_split = 0 " open in new horizontal split
let g:netrw_altv = 1 " open splits on the right
let g:netrw_liststyle = 3 " tree view
let g:netrw_preview = 1
let g:netrw_list_hide = netrw_gitignore#Hide()
let g:netrw_list_hide += ',\(^\|\s\s\)\zs\.\S\+'
let g:netrw_list_hide += ',\.git'
let g:netrw_list_hide += ',\.DS_Store'
let g:netrw_list_hide += ',node_modules'
let g:netrw_list_hide += ',\.gem,\.bundle'
let g:netrw_winsize = 75
let g:netrw_wiw = 25

nnoremap <leader><F2> :exe "Vexplore " expand('%:p:h') <cr>
nnoremap <leader>k :exe "Sexplore " expand('%:p:h') <cr>
nnoremap <leader>. :exe "Ntree " expand('%:p:h') <cr>
nnoremap <leader>m :exe "vs " expand('%:p:h') <cr>
nnoremap <leader>l :netrw-refresh<cr>
