# -*- mode: sh -*-

source $PREFIX/etc/bash.bashrc

export PS1='\W \$ '
export PATH="${HOME}/bin:${PATH}"
export EDITOR="vim"
export VISUAL="vim"
export PAGER="${PREFIX}/bin/less"
export GPG_TTY=$(tty)
export CLICOLOR_FORCE=1
export GTK_THEME=Adwaita:dark

# For Emacs coterm + comint buffers: makes less prompt recognizable → auto char-mode works
export LESS="FRXim"

# Ensure TERM is correct inside Emacs (coterm sets it, but guard against overrides)
if [[ -n "$INSIDE_EMACS" && "$INSIDE_EMACS" == *,comint* ]]; then
  # export TERM="eterm-color"
  export TERM="xterm-256color"
fi

# Disable Next.js telemetry
export NEXT_TELEMETRY_DISABLED=1

if [ -n "$EAT_SHELL_INTEGRATION_DIR" ]; then
  source "$EAT_SHELL_INTEGRATION_DIR/bash"
fi

my_emacs_run() {
  if [ -t 0 ]; then
    eval $EDITOR
  else
    eval $VISUAL
  fi
}

alias pkgu="pkg update"
alias pkgup="pkg upgrade"
alias pkgc="pkg autoclean"
alias pkgls="pkg list-installed"
alias pkglsi="pkgls | grep '\[installed\]'"
alias pkgs="pkg search "
alias pkgf="pkg files "
alias pkgd="pkg show "
alias pkgi="pkg install "
alias pkgrm="pkg uninstall "
alias pkglsu="apt list --upgradable"
alias e="my_emacs_run"
alias grep='grep --color=always'
alias g="git --no-pager"
alias git='git --no-pager'  # prevents pager issues
alias ls="ls --color=always"

# list ssh tunnels
alias ssh-ls="ps -ef | grep '[s]sh'"

# Delete all emails market by notmuch with deleted tag
alias notmuch-rm="notmuch search --format=text0 --output=files tag:deleted | xargs -0 --no-run-if-empty rm; notmuch new"

# Strip isync IDs from all files in current folder
alias isync-strip="find . -name '*U=*:*' -exec bash -c 'mv \"\$1\" \"\${1%,U=*}\"' _ {} \;"