(unbind-key "C-x c")
(unbind-key "C-x <C-left>")
(unbind-key "C-x <C-right>")
(unbind-key "<kp-end>")
(unbind-key "<kp-home>")
(unbind-key "<end>")
(unbind-key "<home>")
(unbind-key "C-x C-'")
(unbind-key "<S-up>")
(unbind-key "<S-down>")
(unbind-key "C-x C-l")
;; (unbind-key "C-x <down>")

(when (boundp 'global-undo-tree-mode)
  (global-undo-tree-mode -1))

(provide 'my-cleanup)
