(defvar my/org-base-path "~/Documents/emacs")
(defvar my/tools-path "~/.emacs.d/tools/")
(defvar org-agenda-directory (expand-file-name "agenda" my/org-base-path))
(defvar org-directory (expand-file-name "orgs" my/org-base-path))
(defvar my/tmp-base-path (expand-file-name "tmp" my/org-base-path))
(defvar my/drills-base-path (expand-file-name "drills" my/org-base-path))

(defvar my/org-english-drill-file-path (expand-file-name "english_drill.org" my/drills-base-path))

(defvar my/org-active-file-path (expand-file-name "active.org" org-agenda-directory))
(defvar my/org-repeatables-file-path (expand-file-name "repeat.org" org-agenda-directory))
(defvar my/org-anniversaries-file-path (expand-file-name "anniversaries.org" org-agenda-directory))
(defvar my/org-languages-file-path (expand-file-name "languages.org" org-agenda-directory))
(defvar my/org-inbox-file-path (expand-file-name "inbox.org" org-agenda-directory))
(defvar my/org-knowledge-review-file-path (expand-file-name "knowledge_reviews.org" org-agenda-directory))
(defvar my/org-yearly-goals-file-path (expand-file-name "yearly_goals.org" org-agenda-directory))

(defvar my/org-diet-log-file-path (expand-file-name "diet.org" org-directory))
(defvar my/org-tasks-file-path (expand-file-name "someday.org" org-directory))
(defvar my/org-projects-file-path (expand-file-name "projects.org" org-directory))
(defvar my/org-contacts-file-path (expand-file-name "contacts.org.gpg" org-directory))
(defvar my/org-blog-file-path (expand-file-name "blog.org" org-directory))
(defvar my/org-journal-file-path (expand-file-name "journal.org.gpg" org-directory))
(defvar my/org-journal-dating-file-path (expand-file-name "journal_dating.org.gpg" org-directory))
(defvar my/org-media-file-path (expand-file-name "media.org" org-directory))
(defvar my/org-tools-file-path (expand-file-name "tools.org" org-directory))
(defvar my/org-review-file-path (expand-file-name "reviews.org.gpg" org-directory))

(defvar my/local-config-file-path (expand-file-name "local-config.el" user-emacs-directory))
(defvar my/org-goals-file-path (expand-file-name "goals.org" org-directory))
(defvar my/org-knowledge-file-path (expand-file-name "knowledge.org" org-directory))
(defvar my/org-quotes-file-path (expand-file-name "quotes.org" org-directory))
(defvar my/org-projects-folder (expand-file-name "projects" my/org-base-path))

(defvar my/org-project-become-confident-pua (expand-file-name "become_confident_pua.org" my/org-projects-folder))
(defvar my/org-project-trip-nottingham (expand-file-name "trip_to_nottingham.org" my/org-projects-folder))
(defvar my/org-project-trip-edinburgh (expand-file-name "trip_to_edinburgh.org" my/org-projects-folder))
(defvar my/org-project-setup-digital-agency (expand-file-name "setup_digital_agency.org.gpg" my/org-projects-folder))
(defvar my/org-project-setup-freelance (expand-file-name "setup_freelance.org.gpg" my/org-projects-folder))
(defvar my/org-project-launch-amazon-business (expand-file-name "launch_amazon_business.org.gpg" my/org-projects-folder))
(defvar my/org-project-switch-to-self-accounting (expand-file-name "switch_to_self_accounting.org.gpg" my/org-projects-folder))
(defvar my/org-project-change-hosting-provider (expand-file-name "change_hosting_provider.org.gpg" my/org-projects-folder))

(defvar my/org-ledger-base-path (expand-file-name "ledger" my/org-base-path))
(defvar my/ruby-gems-path "~/.rbenv/versions/2.3.3/bin/")

(provide 'my-path)
